# Generated by Django 5.0.8 on 2024-10-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('netbox_plugin_buildingplan', '0004_buildingplandevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingplan',
            name='tenant',
        ),
        migrations.AddField(
            model_name='buildingplan',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_plans', to='dcim.site'),
            preserve_default=False,
        ),
    ]
