# Generated by Django 5.0.8 on 2024-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_plugin_buildingplan', '0005_remove_buildingplan_tenant_buildingplan_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingplandevice',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
