# Generated by Django 5.0.8 on 2024-10-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('netbox_plugin_buildingplan', '0006_buildingplandevice_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingplandevice',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='buildingplandevice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='DeviceIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('icon_path', models.CharField(max_length=255)),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='dcim.devicerole')),
            ],
        ),
    ]
